{"name": "Неуспешная аутентификация под несуществующими данными", "status": "passed", "start": 1721957317910, "stop": 1721957318087, "uuid": "64f6baa6-1247-4f26-8090-73d3aaf05904", "historyId": "43c78cbc880d86d673bc980eb8a4cded", "testCaseId": "43c78cbc880d86d673bc980eb8a4cded", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_login_with_invalid_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "Ermaksmak-PC"}, {"name": "thread", "value": "25000-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}